Repository PositiveTechnologies/PT.PM, pull requests merged in 2018-06, with the labels that each got.

#137 Added JSON dumping option
  Sources/PT.PM.Cli.Common/CliParameters.cs
  Sources/PT.PM.Cli.Common/CliProcessorBase.cs
  Sources/PT.PM/Workflow.cs
  Sources/PT.PM/WorkflowBase.cs
  Sources/PT.PM/WorkflowResultBase.cs
Labels: serialization

#144 Added CLangs project.
  Sources/PT.PM.CLangsParseTreeUst/C.cs
  Sources/PT.PM.CLangsParseTreeUst/CPlusPlus.cs
  Sources/PT.PM.CLangsParseTreeUst/ObjectiveC.cs
  Sources/PT.PM.CLangsParseTreeUst/PT.PM.CLangsParseTreeUst.csproj
  Sources/PT.PM.CSharpParseTreeUst/Aspx.cs
  Sources/PT.PM.CSharpParseTreeUst/CSharp.cs
  Sources/PT.PM.Common/CodeRepository/DirectoryCodeRepository.cs
  Sources/PT.PM.Common/CodeRepository/DummyCodeRepository.cs
  Sources/PT.PM.Common/CodeRepository/FileCodeRepository.cs
  Sources/PT.PM.Common/CodeRepository/MemoryCodeRepository.cs
  Sources/PT.PM.Common/CodeRepository/SourceCodeRepository.cs
  Sources/PT.PM.Common/Language.cs
  Sources/PT.PM.Common/LanguageUtils.cs
  Sources/PT.PM.Common/Uncertain.cs
  Sources/PT.PM.JavaParseTreeUst/Java.cs
  Sources/PT.PM.JavaScriptParseTreeUst/JavaScript.cs
  Sources/PT.PM.PatternEditor/ViewModels/MainWindowViewModel.cs
  Sources/PT.PM.PatternEditor/ViewModels/PatternViewModel.cs
  Sources/PT.PM.PatternEditor/ViewModels/PatternsViewModel.cs
  Sources/PT.PM.Patterns/CLangsPatterns.cs
  Sources/PT.PM.Patterns/DefaultPatternRepository.cs
  Sources/PT.PM.Patterns/PT.PM.Patterns.csproj
  Sources/PT.PM.PhpParseTreeUst/Html.cs
  Sources/PT.PM.PhpParseTreeUst/Php.cs
  Sources/PT.PM.PlSqlParseTreeUst/PlSql.cs
  Sources/PT.PM.TSqlParseTreeUst/TSql.cs
  Sources/PT.PM.Tests/LanguageTests.cs
  Sources/PT.PM.Tests/SourceCodeRepositoryTests.cs
  Sources/PT.PM.sln
  Sources/PT.PM/ParserLanguageDetector.cs
  Sources/PT.PM/WorkflowBase.cs
Labels: new-feature

#147 UST JSON improvements
  Sources/PT.PM.Common/Json/JsonBaseSerializer.cs
  Sources/PT.PM.Common/Json/JsonUtils.cs
  Sources/PT.PM.Common/Json/TextSpanJsonConverter.cs
  Sources/PT.PM.Common/Json/UstJsonConverter.cs
  Sources/PT.PM.Common/Json/UstJsonConverterReader.cs
  Sources/PT.PM.Common/Json/UstJsonConverterWriter.cs
  Sources/PT.PM.Common/Json/UstJsonKeys.cs
  Sources/PT.PM.Common/Json/UstJsonSerializer.cs
  Sources/PT.PM.Common/TextUtils.cs
  Sources/PT.PM.Matching/Json/JsonPatternSerializer.cs
  Sources/PT.PM.Matching/Json/PatternBaseJsonConverter.cs
  Sources/PT.PM.Matching/Json/PatternJsonConverterReader.cs
  Sources/PT.PM.Matching/Json/PatternJsonConverterWriter.cs
  Sources/PT.PM.Matching/Json/PatternJsonUtils.cs
  Sources/PT.PM.Matching/PatternsRepository/JsonPatternsRepository.cs
  Sources/PT.PM.PatternEditor/ViewModels/MainWindowViewModel.cs
  Sources/PT.PM.Tests/JsonTests.cs
  Sources/PT.PM/WorkflowBase.cs
Labels: refactoring, serialization

#153 Patterns Serialization
  Sources/PT.PM.Cli.Common/CliParameters.cs
  Sources/PT.PM.Cli.Common/CliProcessorBase.cs
  Sources/PT.PM.Common/CodeFile.cs
  Sources/PT.PM.Common/Json/CodeFileJsonConverter.cs
  Sources/PT.PM.Common/Json/UstJsonConverterReader.cs
  Sources/PT.PM.Common/Json/UstJsonConverterWriter.cs
  Sources/PT.PM.Common/LanguageUtils.cs
  Sources/PT.PM.Matching/Json/JsonPatternSerializer.cs
  Sources/PT.PM.Matching/Json/PatternJsonConverterReader.cs
  Sources/PT.PM.Matching/Json/PatternJsonConverterWriter.cs
  Sources/PT.PM.Matching/PatternNormalizer.cs
  Sources/PT.PM.Matching/PatternRoot.cs
  Sources/PT.PM.Matching/Patterns/IRegexPattern.cs
  Sources/PT.PM.Matching/Patterns/PatternCommentRegex.cs
  Sources/PT.PM.Matching/Patterns/PatternIdRegexToken.cs
  Sources/PT.PM.Matching/Patterns/PatternIntRangeLiteral.cs
  Sources/PT.PM.Matching/Patterns/PatternStringRegexLiteral.cs
  Sources/PT.PM.Matching/Patterns/PatternUst.cs
  Sources/PT.PM.Matching/PatternsRepository/JsonPatternsRepository.cs
  Sources/PT.PM.Tests/JsonTests.cs
  Sources/PT.PM/WorkflowBase.cs
Labels: cli, patterns, refactoring, serialization
